
dist: trusty
sudo: false
language: cpp

git:
  submodules: false

cache:
  directories:
    - "${HOME}/google-cloud-sdk"

env:
  - PATH=${HOME}/google-cloud-sdk/bin:${PATH}

before_install:
  - if [ ! -d "${HOME}/google-cloud-sdk/bin" ]; then
      curl "https://sdk.cloud.google.com";
    fi | bash

script: ./bin/travis-ci
