
dist: trusty
sudo: false
language: cpp

git:
  submodules: false

cache:
  directories:
    - "${HOME}/google-cloud-sdk"

env:
  - PATH=${HOME}/google-cloud-sdk/bin:${PATH}

before_install:
  - if [ ! -d "${HOME}/google-cloud-sdk/bin" ]; then
      export CLOUDSDK_CORE_DISABLE_PROMPTS=1;
      export CLOUDSDK_INSTALL_DIR="${HOME}/google-cloud-sdk";
      curl "https://sdk.cloud.google.com" | bash;
    fi

script: ./bin/travis-ci
